name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> $HOME/.ssh/known_hosts

      - name: Deploy Backend (Flask via PM2)
        run: |
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
            cd /home/${{ secrets.VPS_USER }}/python/coba-auto-deploy &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            pm2 restart auto-deploy
          "
